name: "Mkumar2022-7's Action In Action"
description: 'Greets someone and returns always 42'
inputs:
  who-to-greet: # id of the input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer: # id of input
    description: 'The answer to everything (always 42)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    
